// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyAMSFeP_rFdhMdW3T44J5uP702N4y5Q9f4',
    appId: '1:909516476182:android:8df91fea690a9e1c5c4a37',
    messagingSenderId: '909516476182',
    projectId: 'start-with-fire-589f3',
    storageBucket: 'start-with-fire-589f3.appspot.com',
  );

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyBBrWOHqgsVaslVa50aWyFZ3ZFPwDVaJHg',
    appId: '1:909516476182:web:869af2feb36e46145c4a37',
    messagingSenderId: '909516476182',
    projectId: 'start-with-fire-589f3',
    authDomain: 'start-with-fire-589f3.firebaseapp.com',
    storageBucket: 'start-with-fire-589f3.appspot.com',
    measurementId: 'G-VHMGC3WBTM',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyAmVmko9dEoxPHo_rXiP9CXuL5m3p8ZKCU',
    appId: '1:909516476182:ios:dda540e8687913955c4a37',
    messagingSenderId: '909516476182',
    projectId: 'start-with-fire-589f3',
    storageBucket: 'start-with-fire-589f3.appspot.com',
    iosBundleId: 'com.example.fireFcm',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyAmVmko9dEoxPHo_rXiP9CXuL5m3p8ZKCU',
    appId: '1:909516476182:ios:dda540e8687913955c4a37',
    messagingSenderId: '909516476182',
    projectId: 'start-with-fire-589f3',
    storageBucket: 'start-with-fire-589f3.appspot.com',
    iosBundleId: 'com.example.fireFcm',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyBBrWOHqgsVaslVa50aWyFZ3ZFPwDVaJHg',
    appId: '1:909516476182:web:f1d1ba1be9cde2af5c4a37',
    messagingSenderId: '909516476182',
    projectId: 'start-with-fire-589f3',
    authDomain: 'start-with-fire-589f3.firebaseapp.com',
    storageBucket: 'start-with-fire-589f3.appspot.com',
    measurementId: 'G-F3V65WGNQ4',
  );

}